addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
notifications:
  email:
    on_success: never
    on_failure: always
branches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "HbmyvpWu7iPYr12O3MJPU9y0C7oER2e7eHRjIr93V8kkeyEdR/splJJrpv7RknkYRG9T3AJElZO392Ntfn/dzv7HlCXJUOpskdtm22BvxPp8alaDQIIqFsEdL39W+zwAX6J2vU9M8zIa0Ffh8mVd0AN8Qe7NkG4IEJFEzmvgecvCCaVshFn+i64IzEyY+UdBbEuxVUMfQ9lMt2JH0QYJKqYUNbuOEyGjcQJZdx4ifoKQqi2gtm2el4XF+PGBUjS8d/zWvzfLd8XNwsvwRF+C2sMUzTnfnqMQ8TfsSefCyDPNHqEM4LPzjJN3V8auRFXVq01JxBmUW6LFJFaq9sCsXzgN0KnJWEcfHueYvb+7IAwHR9jGOGdtG/9LIt+utyHEXm6OtQzTF9R0dJCW6AR9NbbGITZcP6lksUPX6/REB6OvbhD2JPGlx4Kvx2zkb9pUlQxt5FWgFkqfiHjaqCcPYF5WW0V/Q9rGOkz++ji03KOyxthMRjiiBVTNb5lJhajGeP/UtZqjBMH5P1MeXVEV5LbjoEV34zbO2KVuj4EGxvTNyaCGC4Er/4iXbSbJ8pFBV810E/Ql7mAjLT6B7oRA3oN19AofMMLFjf66e5gQhEuDHoo+Y/2VjeaVravS+64iupWYcLrin0bmDJJ78Z53vJRJ4zjfoAKUs9aeKKIAOkc="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
