language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
notifications:
  email:
    on_success: never
    on_failure: always
branches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: make test

deploy:
  provider: releases
  api_key:
    secure: "E1nSH0h214/5P3imRw28tQZ4+AmDRDM0DZtG5f55G/8mT2ClSUmJ2w3524FgS6Pxfrh0Bn9ovhqW5MPr0aoug4UHJoOVqubteuY42RXcABv3rRDW2UNvMMoax8ygZui5yhlH9JqsjTD4lwj4NDSbtQ2tdxJNdSBXeDnpZXQM44GE8zCcLlS0905pb5XotmEZZh4eGNLTKqa6sPrJ6doM1tv7xR2u7QKoXlUN3j6OMwy1tF17GF2uZpwwKmx6E3yQAXq5iy58QXhil3c0SQyxVTQHJ+WlQypi9i6IvkJ4eI2Es5KZxs0kfHGvImtFYFpJy2qcaX6oWbI/EVQTVCfiCBo/soO1xrgCv/7BKFpuwKC38wiMJOOYO6q5vQ6pJV0nredtye1tyNaRvb0tIdLWkdpGPxXuqvxAoKixH7jMgePw/qhqUFhHcmZQa2lc8/UYI7fvC6xPDOkpjqzq+l86xmJvWtJLfUxSdAHtppnXiPUg7y+o3TfVLHQJ3NyrnY8lJCW+ulmoDCDv8wHk/mi+F+V2MLpXi71vf1Tnimh22elbhVxNUYT6xKFzKtt5qFVpC/t0ovkIbNGqHYvspD9SusFrH8k9orre/tkl7f9yvtqcqroYJI9albKcQb3s9p1s+NGvmSi3iPdywHuf1eR99JEAmhTpkGi9NdaLIDngz10="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
