language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
notifications:
  email:
    on_success: never
    on_failure: always
branches:
  only:
  - master

before_install:
- source scripts/ci/environment.sh
- make build-builder

install: make build

script: true

deploy:
  provider: releases
  api_key:
    secure: "hHMTQTvAt8nFovarm6qhQndTfXoyar7PpkpEbIc0drL+LQRyXapfcwx6C6PWwg82y93bvOITL/9N5hKZBS6hvVE7tQB5ZHy6ofjHo9sVM1PIuq2p3XrrHP7CYOgi7XHvd0lQhrcDWJ6ox9ARQWtIbRv5C51bAxv19jeKUTVJMvbVYIx2n/ferx9bZquebUqr0nKb+j+wB7kCGSXA5rihO0c4ML3U6J4o6j9bzhNxrd0hmGSAghRWQOaN5eRx7XjbMGGaHj1RpdQcQ4ezfq5YyQ9ob/vf1Cpowj8DyscaDN91H1F+Bi8hJ25FfV0OvCutbc1gR3nSn2sNCpechpBVBbizAB+qthrtlRyEfnSkVoB4rBFySqA6/4106kXeOnVxGpbs8caPViIa6ZVixfGyNIZi0uItsGVqnx/P8P9wuMdX/W03sy1hZvVB7HDm/mk8MpHRlztyqI82eOfmWZT5g4UXlD4+OVgYFJjew5PtoAu5XW0GMkLxePd23OsmcgAVVUYX0zGGa1sbdq60doUKmsSpIPv/eMBAKiGcFWhJuxkPoNESpTK3OnQPxOmaZoW32uHF4ITnBVR4CFYBAgdtWq4UId+ofVBoLEK5POTexnpZZycy2sjf+/5XOzAEhjgzzSyguKM8Tc/WQORWZk2T0Tmbp2xEZkjPbMs6AadO5Y8="
  file: overridehostname/bin/liboverridehostname.so.1
  skip_cleanup: false
  on:
    tags: true
